In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [149]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [150]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())

In [151]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [152]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis = 1),df.price)

LinearRegression()

In [153]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [154]:
reg.intercept_


221323.00186540425

In [155]:
reg.predict([[3000,3,40]])

C:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [156]:
112.06244194*3000+23388.88007794*3+ -3231.71790863*40+221323.00186540425

498408.25157402427

In [157]:
reg.predict([[2500,4,5]])

C:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

## Exercise

In [159]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [160]:
df = df.rename({'test_score(out of 10)': 'Test_score','interview_score(out of 10)': 'Interview_score','salary($)':'salary'},axis =1)
df

experience  Test_score  Interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [161]:
df.Test_score.median()

8.0

In [162]:
df.Test_score= df.Test_score.fillna(df.Test_score.median())
df

experience  Test_score  Interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [163]:
df.experience = df.experience.fillna('zero')
df

experience  Test_score  Interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [164]:
# #!pip install word2number
# from word2number import w2n
# print(w2n.word_to_num('two point three'))

In [165]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  Test_score  Interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [166]:
reg = linear_model.LinearRegression()
# reg.fit([['experience','Test_score','Interview_score']],df.salary)
reg.fit(df.drop('salary',axis = 1),df.salary)

LinearRegression()

In [186]:
reg.predict([[2,9,6]])

C:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [188]:
reg.predict([[12,10,10]])

C:\Users\parth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])